[dependencies]
regex = "1"
tempfile = "3"

[dependencies.tokio]
features = ["full"]
version = "1"

[package]
authors = ["Sora Tonami <ms0503@outlook.com>"]
edition = "2024"
name = "wezimgcat-wrapper"
resolver = "3"
version = "0.2.0"
