binop_separator = "Front"
brace_style = "SameLineWhere"
combine_control_expr = true
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
disable_all_formatting = false
edition = "2021"
empty_item_single_line = false
fn_args_layout = "Tall"
fn_params_layout = "Tall"
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = false
format_code_in_doc_comments = true
format_generated_files = false
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "One"
hard_tabs = false
hex_literal_case = "Lower"
imports_granularity = "Item"
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
match_arm_blocks = false
match_arm_leading_pipes = "Never"
match_block_trailing_comma = false
merge_derives = true
merge_imports = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
skip_children = false
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_lit_single_line = false
tab_spaces = 4
trailing_comma = "Never"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
where_single_line = false
wrap_comments = true
