updates:
  - directory: "/"
    package-ecosystem: "nix"
    schedule:
      interval: "weekly"
  - directory: "/pkgs/wezimgcat-wrapper"
    package-ecosystem: "cargo"
    schedule:
      interval: "weekly"
version: 2
