updates:
  - directory: "/"
    ignore:
      - dependency-name: "nixpkgs-blender3"
    package-ecosystem: "nix"
    schedule:
      interval: "weekly"
  - directory: "/pkgs/wezimgcat-wrapper"
    package-ecosystem: "cargo"
    schedule:
      interval: "weekly"
version: 2
