jobs:
  update:
    permissions:
      contents: "write"
    runs-on: "ubuntu-24.04"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v6"
      - name: "Install Nix"
        uses: "cachix/install-nix-action@v31"
        with:
          extra_nix_config: |
            accept-flake-config = true
            experimental-features = flakes nix-command pipe-operators
          github_access_token: "${{ secrets.GITHUB_TOKEN }}"
          nix_path: "nixpkgs=channel:nixos-unstable"
      - name: "Configure Git"
        run: |
          git config user.email \
            "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
      - name: "Update Nix Flakes"
        run: |
          nix flake update
          git add flake.lock
          git commit -m "chore: update flakes" || :
      - name: "Update packages"
        run: |
          echo "::group::Sync sources"
          nix run nixpkgs#nvfetcher
          git add _sources/
          echo "::endgroup::"
          echo "::group::Run update scripts"
          printf "== Update Microsoft Edge Dev\n"
          ./pkgs/microsoft-edge-dev/update.sh
          git add pkgs/microsoft-edge-dev/default.nix
          echo "::endgroup::"
          echo "::group::Sync cargo hashes"
          while :; do
            is_changed=false
            for pkg in $(
              nix eval --json --impure .#lib.cargoHashes \
                --apply 'cargoHashes: (cargoHashes {
                  system = builtins.currentSystem;
                }).hashes' \
              | jq -r 'to_entries[] | .key + "," + .value'
            ); do
              name=${pkg%,*}
              current_hash=${pkg#*,}
              printf "== Check %s (%s)\n" "$name" "$current_hash"
              path=$(
                nix eval --impure .#lib.cargoHashes \
                  --apply 'cargoHashes: (cargoHashes {
                    system = builtins.currentSystem;
                  }).get-hash "'"$name"'"' \
                | sed 's/^«derivation \(.*\)»$/\1/'
              )
              msg=$(nix build "${path}^out" 2>&1 >/dev/null)
              hash=$(<<<"$msg" grep got: | awk '{print $2}')
              if [[ $current_hash = "$hash" ]]; then
                printf "==== Up-to-date\n"
                continue
              fi
              is_changed=true
              printf "==== Update to %s\n" "$hash"
              sed -i \
                's:^\( \+\)'"$name"' = ".*";$:\1'"$name"' = "'"$hash"'";:' \
                lib/cargo-hashes.nix
            done
            if ! "$is_changed"; then
              printf "== Sync completed\n"
              break
            fi
            printf "== Resync needed\n"
          done
          git add lib/cargo-hashes.nix
          echo "::endgroup::"
          echo "::group::Sync bazel hashes"
          while :; do
            is_changed=false
            for pkg in $(
              nix eval --json .#lib.bazelHashes \
                --apply builtins.attrNames \
              | jq -r '.[]'
            ); do
              printf "== Check %s\n" "$pkg"
              if msg=$(nix build ".#${pkg}.deps" 2>&1 >/dev/null); then
                printf "==== Up-to-date\n"
                continue
              fi
              is_changed=true
              hash=$(<<<"$msg" grep got: | awk '{print $2}')
              printf "==== Update to %s\n" "$hash"
              sed -i \
                's:^\( \+\)'"$pkg"' = ".*";$:\1'"$pkg"' = "'"$hash"'";:' \
                lib/bazel-hashes.nix
            done
            if ! "$is_changed"; then
              printf "== Sync completed\n"
              break
            fi
            printf "== Resync needed\n"
          done
          git add lib/bazel-hashes.nix
          echo "::endgroup::"
          git commit -m "chore: update packages" || :
      - name: "Push to repository"
        run: |
          git push origin main
name: "Update Nix Flakes and packages"
on:
  workflow_dispatch:
